### ISSUE TITLE
請問車子座標的長度單位是什麼？

### ISSUE THREAD

**Issue by tanchihpin0517** [yen900611/Maze_Car#2]
我注意到在scene_info裡面的x跟y的單位跟sensor的單位沒有對上，請問車子座標用的單位是什麼？

**Comment by yen900611** [comment]
X-Y座標系統所使用的單位為公分，每公分換算為20px。

tanchihpin0517 ***@***.***> 於 2021年11月20日 週六 下午8:21 寫道：

**Comment by tanchihpin0517** [comment]
但我自己測試，讓車子朝著上方的水平牆面前進，F_sensor的數值從97變成14，而車子的座標卻只有從-22變成-6，看起來兩個數值的單位沒有對上(畫面上sensor的單位也是公分)

**Comment by yen900611** [comment]
那可能要等我測試一下發生的狀況，再跟你回覆

tanchihpin0517 ***@***.***> 於 2021年11月20日 週六 下午8:35 寫道：

**Comment by kylingithub** [comment]
finish
